/* stores the previous and new row states generated by user changes */
CREATE TABLE user_audit (
    audit_id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    operation VARCHAR(10) NOT NULL,
    old_data JSONB,
    new_data JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

/* executes automatically whenever the users trigger is activated */
CREATE FUNCTION audit_user_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO user_audit (user_id, operation, old_data, new_data)
        VALUES (NEW.id, TG_OP, NULL, TO_JSONB(NEW));
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO user_audit (user_id, operation, old_data, new_data)
        VALUES (NEW.id, TG_OP, TO_JSONB(OLD), TO_JSONB(NEW));
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO user_audit (user_id, operation, old_data, new_data)
        VALUES (OLD.id, TG_OP, TO_JSONB(OLD), NULL);
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$;

/* connects insert, update, and delete events to the audit function */
CREATE TRIGGER users_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON users
FOR EACH ROW
EXECUTE FUNCTION audit_user_changes();
